Entity/Post.php
<?php

namespace BetaMFD\WikiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Post
 *
 * @ORM\Table(name="wiki_post")
 * @ORM\Entity(repositoryClass="\BetaMFD\WikiBundle\Repository\PostRepository")
 */
class Post
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\ManyToOne(targetEntity="BetaMFD\WikiBundle\Entity\PostType")
     * @ORM\JoinColumn(referencedColumnName="id", nullable=true)
     */
    private $type;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50, nullable=false, unique=true)
     */
    private $slug;

    /**
     * @var integer
     *
     * I've found that this has to be nullable so that it can save then update with the new ID
     *
     * @ORM\OneToOne(targetEntity="BetaMFD\WikiBundle\Entity\PostVersion", fetch="EAGER", cascade={"persist"})
     * @ORM\JoinColumn(name="version_id", referencedColumnName="id", nullable=true)
     */
    private $currentVersion;

    /**
     * @var integer
     *
     * If the slug changes, the old slug should redirect to the new one, so this can signal that
     *
     * @ORM\ManyToOne(targetEntity="BetaMFD\WikiBundle\Entity\Post")
     * @ORM\JoinColumn(referencedColumnName="id", nullable=true)
     */
    private $redirect;

    /**
     * @var string
     *
     * @ORM\ManyToMany(targetEntity="BetaMFD\WikiBundle\Entity\Tag", inversedBy="posts", cascade={"persist", "remove"})
     * @ORM\JoinTable(name="wiki_posts_tags")
     */
    private $tags;

    /**
     * @ORM\OneToMany(targetEntity="BetaMFD\WikiBundle\Entity\PostVersion",
     *  mappedBy="post", cascade={"persist"})
     */
    private $versions;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $topCurrentVersion = 0;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $topMajor = 0;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $topMinor = 0;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $topPatch = 0;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $topMeta;

    /**
     * This is to try to prevent race conditions
     * @var integer
     * @ORM\Column(type="integer")
     * @ORM\Version
     */
    protected $changeVersion;

    public function __construct()
    {
        $this->tags = new \Doctrine\Common\Collections\ArrayCollection();
        $this->versions = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function __toString()
    {
        return $this->getCurrentVersion()->getTitle();
    }

    public function isNew()
    {
        return empty($this->id);
    }

    public function getSemanticVersion()
    {
        $version = $this->topMajor . '.' . $this->topMinor . '.' . $this->topPatch;
        if (!empty($this->topMeta)) {
            $version .= '-' . $this->topMeta;
        }
        return $version;
    }

    public function setNewMajorVersion(PostVersion $version, $meta = null)
    {
        $this->setNewVersion($version);
        $major = ++$this->topMajor;
        $version->setMajor($major);
        $this->topMinor = 0;
        $version->setMinor(0);
        $this->topPatch = 0;
        $version->setPatch(0);
        $this->topMeta = $meta;
        $version->setMeta($meta);
    }

    public function setNewMinorVersion(PostVersion $version, $meta = null)
    {
        $this->setNewVersion($version);
        $version->setMajor($this->topMajor);
        $minor = ++$this->topMinor;
        $version->setMinor($minor);
        $this->topPatch = 0;
        $version->setPatch(0);
        $this->topMeta = $meta;
        $version->setMeta($meta);
    }

    public function setNewPatchVersion(PostVersion $version, $meta = null)
    {
        $this->setNewVersion($version);
        $version->setMajor($this->topMajor);
        $version->setMinor($this->topMinor);
        $patch = ++$this->topPatch;
        $version->setPatch($patch);
        $this->topMeta = $meta;
        $version->setMeta($meta);
    }

    public function setNewMetaVersion(PostVersion $version, $meta = null)
    {
        $this->setNewVersion($version);
        $version->setMajor($this->topMajor);
        $version->setMinor($this->topMinor);
        $version->setPatch($this->topPatch);
        $this->topMeta = $meta;
        $version->setMeta($meta);
    }

    private function setNewVersion(PostVersion $version)
    {
        $this->addVersion($version);
        $this->setCurrentVersion($version);
        $topV = ++$this->topCurrentVersion;
        $version->setCurrentVersion($topV);
        $version->setPost($this);
    }

    #########################################################################
    #                            Getters/Setters                            #
    #########################################################################

    /**
     * Get the value of Id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of Type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of Type
     *
     * @param integer type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get the value of Slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set the value of Slug
     *
     * @param string slug
     *
     * @return self
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get the value of CurrentVersion
     *
     * @return integer
     */
    public function getCurrentVersion()
    {
        return $this->currentVersion;
    }

    /**
     * Get the value of CurrentVersion
     *
     * @return integer
     */
    public function getVersion()
    {
        return $this->currentVersion;
    }

    /**
     * Set the value of CurrentVersion
     *
     * @param integer version
     *
     * @return self
     */
    public function setCurrentVersion($version)
    {
        $this->currentVersion = $version;

        return $this;
    }

    /**
     * Get the value of Tags
     *
     * @return string
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Implodes tags into a string for form editing
     *
     * @return string $tag_list
     */
    public function getTagString()
    {
        $tags = $this->getTags();
        if (!empty($tags)) {
            $tags = $tags->toArray();
            $tag_list = implode(', ', $tags);
            return $tag_list;
        }
        return '';
    }

    /**
     * Resets the $tags ArrayCollection
     *
     * @return $this
     */
    public function clearTags()
    {
        $this->tags = new \Doctrine\Common\Collections\ArrayCollection();

        return $this;
    }

    /**
     * Add tag
     *
     * @param BetaMFD\WikiBundle\Entity\Tag $tag
     *
     * @return Tag
     */
    public function addTag(Tag $tag)
    {
        $this->tags[] = $tag;

        return $this;
    }

    /**
     * Remove Tag
     *
     * @param BetaMFD\WikiBundle\Entity\Tag $tag
     */
    public function removeTag(Tag $tag)
    {
        $this->tags->removeElement($tag);
    }

    /**
     * Get the value of Versions
     *
     * @return mixed
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     * Add version
     *
     * @param BetaMFD\WikiBundle\Entity\PostVersion $version
     *
     * @return self
     */
    public function addVersion(PostVersion $version)
    {
        $this->versions[] = $version;

        return $this;
    }

    /**
     * Remove Version
     *
     * @param BetaMFD\WikiBundle\Entity\PostVersion $version
     */
    public function removeVersion(PostVersion $version)
    {
        $this->versions->removeElement($version);
    }

    /**
     * Get the value of Redirect
     *
     * @return integer
     */
    public function getRedirect()
    {
        return $this->redirect;
    }

    /**
     * Set the value of Redirect
     *
     * @param integer redirect
     *
     * @return self
     */
    public function setRedirect($redirect)
    {
        $this->redirect = $redirect;

        return $this;
    }

    /**
     * Get the value of Top Current Version
     *
     * @return integer
     */
    public function getTopCurrentVersion()
    {
        return $this->topCurrentVersion;
    }

    /**
     * Set the value of Top Current Version
     *
     * @param integer topCurrentVersion
     *
     * @return self
     */
    public function setTopCurrentVersion($topCurrentVersion)
    {
        $this->topCurrentVersion = $topCurrentVersion;

        return $this;
    }

    /**
     * Get the value of Top Major
     *
     * @return integer
     */
    public function getTopMajor()
    {
        return $this->topMajor;
    }

    /**
     * Set the value of Top Major
     *
     * @param integer topMajor
     *
     * @return self
     */
    public function setTopMajor($topMajor)
    {
        $this->topMajor = $topMajor;

        return $this;
    }

    /**
     * Get the value of Top Minor
     *
     * @return integer
     */
    public function getTopMinor()
    {
        return $this->topMinor;
    }

    /**
     * Set the value of Top Minor
     *
     * @param integer topMinor
     *
     * @return self
     */
    public function setTopMinor($topMinor)
    {

Entity/PostType.php
<?php

namespace BetaMFD\WikiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * PostType
 *
 * @ORM\Table(name="wiki_post_type")
 * @ORM\Entity
 */
class PostType
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    private $type;

    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $needApproval = 0;


   /**
    * Get the value of Type
    *
    * @return string
    */
    public function __toString()
    {
        return $this->type;
    }

    /**
     * Get the value of Id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of Type
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of Type
     *
     * @param string type
     *
     * @return self
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get the value of Need Approval
     *
     * @return boolean
     */
    public function getNeedApproval()
    {
        return $this->needApproval;
    }

    /**
     * Set the value of Need Approval
     *
     * @param boolean needApproval
     *
     * @return self
     */
    public function setNeedApproval($needApproval)
    {
        $this->needApproval = $needApproval;

        return $this;
    }

}

Controller/PostController.php
<?php

namespace BetaMFD\WikiBundle\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use BetaMFD\WikiBundle\Entity\Post;
use BetaMFD\WikiBundle\Entity\PostType;
use BetaMFD\WikiBundle\Entity\PostVersion;
use BetaMFD\WikiBundle\Utils\Functions;

/**
 * @Route("/wiki/post", name="wiki_post_")
 */
class PostController extends Controller
{
    private $tagService;
    private $em;

    public function __construct(
        \BetaMFD\WikiBundle\Service\TagService $tagService,
        EntityManagerInterface $entityManager
    ) {
        $this->tagService = $tagService;
        $this->em = $entityManager;
    }

    /**
     * @Route("/{type}/edit/{id}",
     *     name="edit",
     *     defaults={"type": "wiki", "id": null}
     *   )
     * @ParamConverter("type",
     *     options={
     *         "mapping": {"type" = "type"}
     *         })
     */
    public function editAction(Request $request, Post $post = null, PostType $type)
    {
        if (empty($post)) {
            $return['post'] = new Post();
            $return['post']->setCurrentVersion(new PostVersion());
            $return['post']->setType($type);
        } else {
            $return['post'] = $post;
        }
        $return['type'] = $type;
        $tree = $this->em->getRepository('BetaMFDWikiBundle:PostCategory')->findTree();
        return $this->render('@BetaMFDWiki/post/edit.html.twig', $return);
    }

    /**
    * @Route("/{type}/submit/{id}",
    *     name="submit",
    *     defaults={"type": "wiki", "id": null}
    *   )
    * @ParamConverter("type",
     *     options={
     *         "mapping": {"type" = "type"}
     *         })
    */
    public function submitAction(Request $request, Post $post = null, PostType $type)
    {
        $submitted = $request->request->all();
        $title = $request->get('_title');
        $slug = $request->get('_slug');
        $comment = $request->get('_comment');
        $tagString = $request->get('_tags');
        $draft = $request->get('_draft');
        $html = $request->get('_html');
        $markup = $request->get('_markup');
        $version = new PostVersion();
        if (empty($post)) {
            //new posts are easiest
            $post = new Post();
            $this->em->persist($post);
            //set type based on URL
            if (empty($type)) {
                //Should I just create a new type?? Or . . . ?
                return new Response(json_encode([
                    'status'=>'fail',
                    'reason' => 'The given type was not found. This error shouldn\'t be possible',
                ]), 404);
            }
            $post->setType($type);
        }

        $this->em->persist($version);
        switch($request->request->get('_version')) {
            case "major":
            $post->setNewMajorVersion($version);
            break;
            case "minor":
            $post->setNewMinorVersion($version);
            break;
            case "patch":
            $post->setNewPatchVersion($version);
            break;
            default:
            //this should probably not be possible.
            return new Response(json_encode([
                'status'=>'fail',
                'reason' => 'Version type was not chosen. Please choose a version.',
            ]), 400);
        }

        $post->setTitle($title);
        $post->setSlug($slug);
        $post->setComment($comment);
        $post->setDraft(!empty($draft) ? true : false);
        $post->setHtml($html);
        $post->setMarkup($markup);
        $post->setUser($this->getUser());
        //set tags using the tag service
        $this->tagService->addTagsToEntity($post, $tagString);

        $this->em->flush();
        return new Response(json_encode([
            'status'=>'success',
        ]));
    }


    /**
     * @Route("/{type}/all", name="all_by_type",
     *     defaults={"type": "wiki"}
     *   )
     * @ParamConverter("type",
      *     options={
      *         "mapping": {"type" = "type"}
      *         })
     */
    public function allTypeAction(PostType $type)
    {
        $posts = $this->em->getRepository('BetaMFDWikiBundle:Post')->findByType($type);

        //reorganize for better display
        foreach ($posts as $post) {
            $category = $post->getCategory();
            $cat = (empty($category)) ? 0 : $category->getCategory();
            $title = $post->getTitle();
            $list[$cat][$title] = $post;
        }
        Functions::ksortRecursive($list);

        $return['type'] = $type;
        $return['list'] = $list;
        return $this->render('@BetaMFDWiki/post/list.html.twig', $return);
    }

    /**
     * @Route("/slug/{slug}", name="slug_test")
     */
    public function slugTestAction($slug = null)
    {
        $post = $this->em->getRepository('BetaMFDWikiBundle:Post')->findOneBySlug($slug);
        if (empty($post)) {
            return new Response(json_encode([
                'status' => 'success',
            ]));
        } else {
            return new Response(json_encode([
                'message' => 'Slug already exists.',
            ]), 409);
        }
    }

    /**
     * @Route("/{slug}",
     *     name="view",
     *     defaults = {"slug": null}
     *     )
     * @ParamConverter("slug",
     *     options={
     *         "mapping": {"slug" = "slug"}
     *         })
    */
    public function viewAction(Post $post)
    {
        return $this->render('@BetaMFDWiki/post/view.html.twig', ['post' => $post]);
    }
}

Resources/views/post/edit.html.twig
{% extends '@BetaMFDWiki/base.html.twig' %}

{% block header_javascripts %}
  {{ parent() }}
  {#}<script src="{{ asset('/bundles/betamfdwiki/js/tui-editor-Editor-all.min.js') }}" type="text/javascript"></script>#}
  <script src="https://uicdn.toast.com/tui-editor/latest/tui-editor-Editor.js"></script>
{% endblock %}
{% block body %}
  <h1>Editing {% if post.isNew %} New Post {% else %}{{ post.Title }}{% endif %}</h1>

  <div id="spinner"></div>

  <form id='form' method="post">
    {% if csrf_token is defined and csrf_token is not empty %}
        <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
    {% endif %}

    <div>
      <label for="title">Title</label>
      <input
          type="text"
          id="title"
          name="_title"
          value="{{ post.title }}"
          required="required"
          autofocus
          {% if post.isNew %}
            oninput="updateSlug(this.value)"
          {% endif %}
      />
    </div>

    <div>
      <label for="slug">Slug</label>
      <input
        type="text"
        id="slug"
        name="_slug"
        value="{{ post.slug }}"
        required="required"
        oninput="testSlug(this.value)"
      />
      <span class="error" id="slug_error"></span>
    </div>

    <div>
      <label for="post">Body</label>
      <div id="editSection"></div>
    </div>

    <div>
      <label for="comment">Comment</label>
      <input type="text" id="comment" name="_comment" required="required" />
    </div>

    <div>
      <label for="version">Version Type</label>
      <select id="version" name="_version" required="required">
        <option value="">Select a version type</option>
        <option value="major">Major</option>
        <option value="minor">Minor</option>
        <option value="patch">Patch</option>
      </select>
    </div>

    <div>
      <label for="tags">Tags</label>
      <input type="text" id="tags" name="_tags" value="{{ post.tagString }}"/>
    </div>

    <div>
      <input type="checkbox" id="draft" name="_draft" value="on" />
      <label for="draft">Is a Draft</label>
    </div>

    <div>
      <input id="submitSave" type="submit" value="Submit" class="btn btn-primary" name="save"/>
      {% if post.isNew %}
          <a href="{{ path('wiki_post_all_by_type', {'type': post.type}) }}">
      {% else %}
          <a href="{{ path('wiki_post_view', {'slug': post.slug}) }}">
      {% endif %}<button type="button">Cancel</button></a>
    </div>
  </form>

  <img src="/bundles/betamfdwiki/images/waiting.svg" wigth="20" height="20" style="display:none"/>

  <script>
      var editor = new tui.Editor({
        el: document.querySelector('#editSection'),
        initialEditType: 'wysiwyg',
        previewStyle: 'vertical',
        codeBlockLanguages: ['SQL', 'PHP', 'javascript'],
        height: '400px',
        initialValue: '{{ post.markup|e('js') }}'
      });
    {% if post.isNew %}
      function updateSlug(newSlug) {
        newSlug = newSlug.replace(/ /g,'');
        document.getElementById("slug").value = newSlug;
        //test this slug to see if it's okay
        document.getElementById("slug_error").innerHTML='<img src="/bundles/betamfdwiki/images/waiting.svg" width=10 height=10 />';
        testSlug(newSlug);
      }
    {% endif %}

    function testSlug(slug) {
        $.ajax({
            type: "POST",
            url: '{{ url('wiki_post_slug_test') }}/' + slug,
            data: {},
            dataType: 'json',
            success: function() {
              document.getElementById("slug_error").innerHTML='OK'
            },
            error: function(response) {
              //console.log(response);
              document.getElementById("slug_error").innerHTML='Taken'
            }
        });
    }

    //when the form is submitted
    $('#form').submit(function(e) {
      //prevent the form from actually submitting so the JS can do things
      e.preventDefault();

      document.getElementById("spinner").innerHTML='<img src="/bundles/betamfdwiki/images/waiting.svg" />';
      var url = "{{ url('wiki_post_submit', {'type': type, 'id': post.id}) }}";

      //get the content of the post
      var content = editor.getValue();
      var html = editor.getHtml();

      //get the rest of the form
      var formSerialize = $(this).serialize();

      //console.log(html);
      //console.log(content);
      var formSerialize = formSerialize + '&_html=' + encodeURIComponent(html);
      var formSerialize = formSerialize + '&_markup=' + encodeURIComponent(content);

      //console.log(formSerialize);
      //post the data
      $.ajax({
          type: "POST",
          url: url,
          data: formSerialize,
          dataType: "json",
          success: function() {
              //forward to article
              var slug = document.getElementById("form").slug.value;
              window.location.href = "{{ url('wiki_post_view') }}/" + slug;
          },
          error: function() {
            alert("Failed to Save");
          }
      }); //end of $.ajax
    }); // end of form submit actions

  </script>

{% endblock %}

Resources/views/post/list.html.twig
{% extends '@BetaMFDWiki/base.html.twig' %}
{% block title %}All {{ type|title }} Posts | {{ parent() }}{% endblock %}

{% block body %}
    <h1>{{ type|title }} Posts</h1>

    {% for cat, array in list %}
        {% if cat is same as (0) %}
          <h2>No Category</h2>
        {% else %}
          <h2>{{ cat }}</h2>
        {% endif %}
        <ul>
          {% for title, post in array %}
            <li><a href="{{ path('wiki_post_view', {'slug': post.slug}) }}">{{ title }}</a></li>
          {% endfor %}
        </ul>
    {% else %}
        There are no {{ type }} posts.
    {% endfor %}
{% endblock %}

Resources/views/post/view.html.twig
{% extends '@BetaMFDWiki/base.html.twig' %}
{% block title %}{{ post.title }} | {{ parent() }}{% endblock %}
{% block header_javascripts %}
  {{ parent() }}
  <script src="https://uicdn.toast.com/tui-editor/latest/tui-editor-Viewer.js"></script>
{% endblock %}
{% block body %}
  <h1>{{ post.title }}</h1>
  <div id="postData">
    Version: {{ post.semanticVersion }} <br />
    Last updated {{ post.date|date('Y-m-d') }} by {{ post.user }}<br />
  </div>
  <div id="modify">
    <a href="{{ path('wiki_post_edit', {'type': post.type, 'id': post.id}) }}">Edit</a><br />
    {#See History<br />
    See Unapproved Drafts<br />#}
  </div>
  <div id="viewerSection"></div>
  <a href="{{ path('wiki_post_edit', {'type': post.type, 'id': post.id}) }}">Edit</a>

  <script>
    var editor = new tui.Editor({
        el: document.querySelector('#viewerSection'),
        viewer: true,
        codeBlockLanguages: ['SQL', 'PHP', 'javascript'],
        initialValue: '{{ post.markup|e('js') }}'
    });

  </script>

{% endblock %}